services:
  - type: static
    name: line-website
    env: static
    buildCommand: npm run build       # คำสั่ง build
    staticPublishPath: dist            # โฟลเดอร์ที่สร้างจาก build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
